.github/workflows/main.yml
pyproject.toml
tests/__init__.py
tests/conftest.py
tests/dask_friendliness.py
tests/mockdata.py

Closes [EODCAPI-57 ](https://eodc.atlassian.net/browse/EODCAPI-57).
Add a basic pipeline to run the (still vacant) test suite.

Setup Github CI

---

.pre-commit-config.yaml
openeo_processes_dask/core.py
openeo_processes_dask/process_implementations/cubes/aggregate.py
tests/conftest.py
tests/general_checks.py
tests/mockdata.py
tests/test_aggregate.py
tests/test_apply.py
tests/test_reduce.py

I've let myself be inspired by the testsuite of https://github.com/makepath/xarray-spatial and have added a couple of test functions and fixtures in that spirit! I've also added an example test for aggregate_temporal_period that uses these.

Setup test fixtures and add example test for `aggregate_temporal_period`

---

pyproject.toml

This is in order to allow installing this library into environments that don't have the exact dependencies!

Make dependencies less restrictive

---

openeo_processes_dask/process_implementations/cubes/experimental.py
openeo_processes_dask/process_implementations/ml/random_forest.py
tests/conftest.py
tests/test_aggregate.py
tests/test_apply.py
tests/test_ml.py
tests/test_reduce.py

This is necessary, because the client still returns inline geojson for this attribute.

Add load_vector_cube to handle inline geojson in fit_regr_random_forest

---

openeo_processes_dask/exceptions.py
openeo_processes_dask/process_implementations/cubes/_filter.py
openeo_processes_dask/process_implementations/cubes/apply.py
openeo_processes_dask/process_implementations/cubes/experimental.py
openeo_processes_dask/process_implementations/cubes/general.py
openeo_processes_dask/process_implementations/cubes/reduce.py

Updates to exceptions

---

tests/test_core.py

Just some tests I had already lying around on a branch!

test: add tests for process decorator

---

openeo_processes_dask/core.py
openeo_processes_dask/process_implementations/cubes/merge.py
openeo_processes_dask/process_implementations/cubes/reduce.py
openeo_processes_dask/process_implementations/math.py
pyproject.toml
tests/test_core.py
tests/test_merge.py
tests/test_reduce.py

Several fixes around how parameters are passed through to subprocesses.

fix: Fix for subprocess execution failures

---

openeo_processes_dask/process_implementations/math.py
tests/test_math.py

fix: Fix clip and add test

---

openeo_processes_dask/process_implementations/cubes/resample.py
openeo_processes_dask/process_implementations/ml/random_forest.py

Updates predict random forest to new callback structure. Neat how much simpler this can be now! :)

fix: Update predict random forest to new callback structure

---

README.md

Add link to parser in readme

---

openeo_processes_dask/process_implementations/arrays.py
openeo_processes_dask/process_implementations/math.py
tests/test_core.py

fix: wrong axis default in reducer processes

---

openeo_processes_dask/core.py
openeo_processes_dask/process_implementations/cubes/apply.py
openeo_processes_dask/process_implementations/math.py
tests/test_apply.py
tests/test_core.py

Closes https://eodc.atlassian.net/browse/EODCAPI-170

feat: Implement apply dimension

---

.github/workflows/release.yml

Need to checkout the submodules in this pipeline too, because otherwise the specs will be missing in the wheels

ci: add recursive checkout to release pipeline

---

openeo_processes_dask/process_implementations/cubes/aggregate.py
tests/test_aggregate.py

Fixes https://github.com/Open-EO/openeo-pg-parser-networkx/issues/44.

fix: add positional params to aggregate_temporal_period

---

docs/decisions/README.md
docs/decisions/handle-nodata-in-rastercubes.md

I've summarised the options and my recommendation for how to deal with nodata going forward in this repo, would be great to get all your eyes on this!

docs: add documentation page for nodata handling

---

openeo_processes_dask/process_implementations/cubes/merge.py
tests/test_merge.py

fix: fix error in merge_cubes if bands are unsortable

---

openeo_processes_dask/process_implementations/cubes/merge.py

Fixing issue https://github.com/Open-EO/openeo-processes-dask/issues/114

fix: in merge_cubes set combine_attrs to no_conflicts

---

openeo_processes_dask/process_implementations/cubes/_xr_interop.py
openeo_processes_dask/process_implementations/cubes/apply.py
openeo_processes_dask/process_implementations/cubes/general.py
tests/test_apply.py
tests/test_dimensions.py
tests/test_math.py

Keep track of the types of dimensions manually and guess only at datacube initialisation, instead of reguessing each time!

Make dimension types static in `.openeo`

---

openeo_processes_dask/__init__.py

This way we cannot forget to update this!

chore: auto-sync __version__ with pyproject.toml

---

openeo_processes_dask/process_implementations/cubes/general.py
tests/test_dimensions.py

Fixing this issue: https://github.com/Open-EO/openeo-processes-dask/issues/187
Test updated to cover this edge case.

Fixing edge case drop_dimension

---

openeo_processes_dask/process_implementations/cubes/apply.py
pyproject.toml

Fix dimension names being wrong in edge cases.

Fix: Apply dim exceptions

---

openeo_processes_dask/process_implementations/arrays.py
tests/test_arrays.py

Not exactly sure how to add array_append to the submodule...

Add array_append

---

.pre-commit-config.yaml
openeo_processes_dask/process_implementations/cubes/resample.py

Fix for https://github.com/Open-EO/openeo-processes-dask/issues/228
Note: I add to add the default python language in the pre-commit configuration otherwise it didn't work in my environment.

Fix resample spatial

---

openeo_processes_dask/process_implementations/math.py
tests/test_math.py

update quantiles to be compliant with v2.0.0 - q is deprecated.

allow quantiles with properties int

---

openeo_processes_dask/process_implementations/cubes/geometries.py
openeo_processes_dask/process_implementations/exceptions.py
tests/conftest.py
tests/test_geometries.py

load_geojson, vector_buffer, vector_reproject

add vector processes

---

openeo_processes_dask/process_implementations/experimental/__init__.py
openeo_processes_dask/process_implementations/experimental/rqadeforestation.py
pyproject.toml
tests/test_reduce.py

This PR aims to add the deforestation detection workflow of the [FAIRSenDD](https://github.com/EarthyScience/FAIRSenDD) project by using its python bindings [rqadeforestation.py](https://github.com/EarthyScience/rqadeforestation.py). 
- continues work of #335 
- closes #335
- see also https://github.com/eodcgmbh/openeo-processes/pull/49

Add rqatrend 
