openeo_processes_dask/exceptions.py, openeo_processes_dask/process_implementations/cubes/general.py, pyproject.toml
Parameter `dimension` renamed to `name`.
Using `.drop` instead of `drop_dims`, which is available only for xArray Datasets https://docs.xarray.dev/en/stable/search.html?q=drop_dims
Solves https://github.com/Open-EO/openeo-processes-dask/issues/13
=> Fixed drop_dimension implementation

openeo_processes_dask/process_implementations/math.py
This made the job referenced in https://discuss.eodc.eu/t/job-queued/520/3 unable to save, because `origin = odc` was getting lost here.
=> Fix ndvi losing attrs

openeo_processes_dask/__init__.py, openeo_processes_dask/core.py, openeo_processes_dask/process_implementations/cubes/_filter.py, openeo_processes_dask/process_implementations/cubes/_xr_interop.py, openeo_processes_dask/process_implementations/cubes/aggregate.py, openeo_processes_dask/process_implementations/cubes/reduce.py, openeo_processes_dask/process_implementations/cubes/resample.py, openeo_processes_dask/process_implementations/cubes/utils.py, pyproject.toml, tests/__init__.py, tests/general_checks.py, tests/test_xr_interop.py
Closes https://eodc.atlassian.net/browse/EODCAPI-111
Some comments:
- This is inspired by https://github.com/opendatacube/odc-geo/blob/develop/odc/geo/_xr_interop.py. 
- I've only added an accessor for DataArray, because Dataset isn't really supported atm, will add that later if it turns out to be necessary!
- Should fix the issue @clausmichele raises in https://github.com/Open-EO/openeo-processes-dask/issues/9#issuecomment-1340982555, with assuming that `datacube` was used to load, `odc-geo` enables the `odc` accessor on any xarrays 
- I'll write some tests for this accessor after some initial feedback!
- Will drop process registry from here when this is merged
=> Add .openeo accessor to DataArray

openeo_processes_dask/process_implementations/cubes/utils.py
Closes https://eodc.atlassian.net/browse/EODCAPI-136
This was a hack I introduced to guarantee some properties of datacubes across processes. This isn’t really necessary anymore, because the .openeo accessor has taken over some of these properties (crs, origin) and the reordering isn't actually required, this was only required for a version of resample_spatial using rioxarray
=> Remove _normalise_output_datacube

openeo_processes_dask/process_implementations/cubes/merge.py, openeo_processes_dask/process_implementations/cubes/resample.py, tests/test_merge.py
"spatial_ref" isn't guaranteed to be updated correctly throughout all the processes, therefore ignore it here completely. Get rid of this once we've settled on a mechanism for keeping track of spatial_ref throughout the process graph.
=> fix: Update spatial_ref in resample_spatial

pyproject.toml
This is to allow shapely 2.0, which caused issues with the install of dask-geopandas 0.3.0
=> chore: Bump openeo-pg-parser-networkx to 2023.1.2

pyproject.toml
This will get rid of the dependency on matplotlib.
=> chore: bump parser version

pyproject.toml
=> chore: bump pg parser to 2023.5.1

openeo_processes_dask/process_implementations/__init__.py, openeo_processes_dask/process_implementations/core.py
Follow-up to conversation in https://github.com/Open-EO/openeo-python-client/pull/434#discussion_r1221658135
@clausmichele what do you think about this structure instead?
=> chore: change logging structure

openeo_processes_dask/process_implementations/cubes/__init__.py, openeo_processes_dask/process_implementations/cubes/load.py, openeo_processes_dask/process_implementations/exceptions.py, pyproject.toml, tests/data/stac/s2_l2a_test_item.json, tests/test_load_stac.py
First version of `load_stac` using `stackstac` to load items generated by queries using `pystac-client`. Another possibility would be using `odc-stac`, but it currently has some limitations which I explained here: https://github.com/opendatacube/odc-stac/issues/54#issuecomment-1602704281
Anyway, we could even consider to support both, depending on the user requirements.
Currently supports only STAC Collections provided by catalogs with the `/query` endpoint for fitlering.
=> feat: add `load_stac`

openeo_processes_dask/process_implementations/ml/random_forest.py
This should speed up the import of this library a bit if xgboost isn't used!
=> chore: move xgb import to occur at runtime

openeo_processes_dask/process_implementations/cubes/general.py, tests/test_dimensions.py
=> chore: remove deprecated `.drop()` function in drop dimension

pyproject.toml
We've had to pin bokeh to "<3" because of https://github.com/dask/distributed/pull/7413. This was fixed in dask 2023.4.0, therefore I think it's time to bump the required dask version for this project and remove the bokeh pin. Moreover this silences a warning on the test suite.
=> chore: bump dask to 2023.4.0 to remove constraint on bokeh

openeo_processes_dask/process_implementations/cubes/_filter.py, tests/mockdata.py, tests/test_apply.py
Address or suppress warnings to get count from 94 down to 14.
=> chore: fix warnings in test suite

openeo_processes_dask/process_implementations/cubes/merge.py, tests/test_merge.py
@LukeWeidenwalker, in load_stac, stackstac loads many additional metadata as data variables/coordinates. It is an advantage when we want to have a complete overview on the dataset but in this case creates an issue when trying to merge different datasets, An example is in this notebook I recently created:
https://github.com/clausmichele/openeo-python-client/blob/add_stac_notebook/examples/notebooks/Client_Side_Processing/client_side_processing_STAC_data_fusion.ipynb
This fix removes the unnecessary coordinates if the merge fails and tries to merge the datacubes again. I spent a lot of time trying to find a more elegant solution, but I couldn't.
=> fix: handle incompatible coords in merge_cubes

openeo_processes_dask/process_implementations/cubes/_filter.py, tests/test_filter.py
I found a special case when `filter_temporal` fails with 
`KeyError: Timestamp('2022-05-10 00:00:00')`
It is probably due to some not conform elements in the temporal dimension.
```python
import openeo
from openeo.local import LocalConnection
local_conn = LocalConnection('')
url = "https://earth-search.aws.element84.com/v1/collections/sentinel-2-l2a"
spatial_extent = {"west": 11.1, "east": 11.5, "south": 46.1, "north": 46.5}
datacube = local_conn.load_stac(url=url,
spatial_extent=spatial_extent)
temporal_extent = ['2022-05-10T00:00:00','2022-06-30T00:00:00']
temporal_slice = datacube.filter_temporal(temporal_extent)
temporal_slice.execute()
```
This PR fixes that special case.
@LukeWeidenwalker could you try that code and confirm that with this PR it solves the issue for you as well? You …
=> fix: special case for filter_temporal

openeo_processes_dask/process_implementations/arrays.py, tests/test_arrays.py
=> fix: support axis keyword in array_contains

openeo_processes_dask/process_implementations/core.py, openeo_processes_dask/process_implementations/ml/__init__.py, openeo_processes_dask/process_implementations/ml/curve_fitting.py, tests/test_ml.py
I've now taken a shot at implementing `fit_curve` too, and thought I'd just start from scratch to see what the problem really is. With just the xarray built-in function `curvefit`, I get throughput of 1000pixels/sec with a vanilla OpenEO dask cluster (6 workers w/ 4CPUs and 12GB RAM each). Dask has added constant memory rechunking a while ago with their [P2P rechunking scheme](https://discourse.pangeo.io/t/rechunking-large-data-at-constant-memory-in-dask-experimental/3266), so I'm somewhat hopeful that this will be okay for larger datacubes too. I haven't tried a truly humonguous dataset yet (the largest I tried was 1million pixels, 2x of what was used in [the SRR2 notebook](https://github.com/openEOPlatform/SRR2_notebooks/blob/main/UC6%20-%20Forest%20Dynamics.ipynb), which took 30 …
=> feat: add fit_curve and predict_curve

openeo_processes_dask/process_implementations/__init__.py
Experimental processes (currently there's only resample_cube_spatial), where not imported/included in the process registry.
=> fix: import experimental processes

openeo_processes_dask/process_implementations/math.py
Fix for this issue: https://github.com/Open-EO/openeo-processes-dask/issues/181
=> Fix ignore_nodata=True

openeo_processes_dask/process_implementations/cubes/general.py
- dimension_labels should return a list, not a raster datacube
- datetimes should be ISO formatted
Found by the new test suite and want to make you aware. I won't have time to add tests, this is more a bug report rather than a full PR.
=> dimension_labels should return a list, datetimes should be ISO formatted

openeo_processes_dask/process_implementations/cubes/mask_polygon.py, pyproject.toml
Culprit line in mask polygon is indexing the y_dim and x_dim values, they're strings so this will fail if you the dimensions are named latitude or longitude. :smile:
=> Bug in mask polygon 

openeo_processes_dask/process_implementations/math.py, tests/test_math.py
Clip correctly in linear_scale_range when inputMax < inputMin
Found by the new test suite and want to make you aware. I won't have time to add tests, this is more a bug report rather than a full PR.
=> Clip correctly in linear_scale_range when inputMax < inputMin

openeo_processes_dask/process_implementations/cubes/aggregate.py, pyproject.toml, tests/test_aggregate.py
Hi team, 
This pull request utilized the new functionality of XVEC for spatial aggregation , addressing all the previously mentioned issues related to dependencies and Dask-based computation.
=> Spatila agg xvec

openeo_processes_dask/process_implementations/cubes/aggregate.py, tests/test_aggregate.py
allow crs in aggregate_spatial as int, str
=> flexible crs in geometries dict in aggregate_spatial
